config/routes.rb
Rails.application.routes.draw do
  get "user_mfa_sessions/new"
  get "user_mfa_sessions/create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "posts#index"
  # root "posts#index"

  resources :users, only: %i[new create destroy] do
    member do
      get :activate
    end
  end
  resources :beatboxers
  resources :posts do
    get :bookmarks, on: :collection
    resource :bookmarks, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resource :profile, only: %i[show edit update]

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
end

app/models/user_mfa_session.rb
class UserMfaSession < GoogleAuthenticatorRails::Session::Base
  # 一旦、親クラスのメソッド継承のみが目的なので記載なし
end

app/controllers/user_mfa_sessions_controller.rb
class UserMfaSessionsController < ApplicationController
  skip_before_action :check_mfa

  def new
    @user = current_user
    session[:google_secret] = @user.google_secret
  end

  def create
    user = current_user
    if user.google_authentic?(params[:mfa_code])
      token = SecureRandom.hex(32)
      user.update!(mfa_session_token: token)
      UserMfaSession.create(user)
      flash[:notice] = "二段階認証に成功しました！"
      redirect_to root_path
    else
      flash[:alert] = "コードが間違っています！"
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/user_mfa_sessions_helper.rb
module UserMfaSessionsHelper
end

app/views/user_mfa_sessions/new.html.erb
<div class="flex justify-center">
  <div class="items-center mt-11 mb-11 gap-8 flex flex-col">
    <%= image_tag @user.google_qr_uri, class: "skeleton" %>

    <%= form_with url: user_mfa_sessions_create_path, method: :get do |f| %>
      <fieldset class="fieldset w-xs dark:bg-black bg-white border border-base-300 p-4 rounded-box">
        <%= f.label :email, "二段階認証コード", class: "fieldset-label" %>
        <%= f.text_field :mfa_code, class: "input", placeholder: "Microsoft Authenticatorの認証コードを入力" %>
        <%= f.submit '送信', class: "btn btn-primary" %>
      </fieldset>
    <% end %>

    <div class="flex">
      <%= link_to "https://apps.apple.com/jp/app/microsoft-authenticator/id983156458" do %>
        <%= image_tag 'appstore_link.png', class: "w-auto h-12 md:w-auto md:h-auto" %>
      <% end %>

      <%= link_to "https://play.google.com/store/apps/details?id=com.azure.authenticator&pcampaignid=web_share" do %>
        <%= image_tag 'googleplay_link.png', class: "w-auto h-12 md:w-auto md:h-auto" %>
      <% end %>
    </div>
  </div>
</div>