config/routes.rb
Rails.application.routes.draw do
  get "user_mfa_sessions/new"
  get "user_mfa_sessions/create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "posts#index"
  # root "posts#index"

  resources :users, only: %i[new create destroy] do
    member do
      get :activate
    end
  end
  resources :beatboxers
  resources :posts do
    get :bookmarks, on: :collection
    resource :bookmarks, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resource :profile, only: %i[show edit update]

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash.now[:notice] = "ユーザーを更新しました！"
      render :edit, status: :created
    else
      flash.now[:alert] = "ユーザーを更新できませんでした！"
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<%= form_with model: @user, url: profile_path, local: true do |f| %>
   <div class="flex justify-center">
      <div class="card dark:bg-black bg-white w-140 shadow-sm items-center mt-11 mb-11 gap-5 flex flex-col">
         <div class="mt-8 w-80 h-80 overflow-hidden rounded-xl">
            <%= image_tag @user.avatar_url, class: "w-80 h-80 object-cover" %>
         </div>
         <div class="w-80 flex flex-col">
            <%= f.label :avatar, "プロフィール画像" %>
            <%= f.file_field :avatar, class: 'file-input w-full', accept: 'image/*' %>
         </div>
         <div class="w-80 flex flex-col">
            <%= f.label :name, "ユーザー名" %>
            <%= f.text_field :name, :placeholder => current_user.name, class: "input w-full" %>
         </div>
         <div class="w-80 flex flex-col">
            <%= f.label :email, "メールアドレス" %>
            <div class="input validator w-full">
               <svg class="h-[1.5em] opacity-50" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                  <g
                     stroke-linejoin="round"
                     stroke-linecap="round"
                     stroke-width="2.5"
                     fill="none"
                     stroke="currentColor"
                  >
                     <rect width="20" height="16" x="2" y="4" rx="2"></rect>
                     <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"></path>
                  </g>
               </svg>
               <%= f.email_field :email, :placeholder => current_user.email, class: "align-middle" %>
            </div>
         </div>
         <div class="w-80 flex flex-col">
            <%= f.label :password, "パスワード" %>
            <%= f.password_field :password, class: "input w-full" %>
         </div>
         <div class="w-80 flex flex-col">
            <%= f.label :password_confirmation, "パスワード確認用" %>
            <%= f.password_field :password_confirmation, class: "input w-full" %>
         </div>
         <div>
            <%= f.submit "更新", class: "btn btn-primary mb-8 mt-3"%>
         </div>
      </div>
   </div>
<%end%>

app/views/profiles/show.html.erb
<div class="flex justify-center mt-14">
  <div class="card dark:bg-black bg-white w-120 items-center shadow-sm">
    <div class="mt-8 w-80 h-80 overflow-hidden rounded-xl">
      <%= image_tag @user.avatar_url, class: "w-80 h-80 object-cover" %>
    </div>
    <div class="card-body items-center text-center gap-5">
      <p class="font-semibold text-2xl"><%= current_user.name %></p>
      <p class="font-semibold text-xl"><%= current_user.email %></p>
    </div>
    <div class="card-actions mb-8 mt-3">
      <button id="profile-edit-button" class="btn btn-primary">
        <%= link_to '編集', edit_profile_path %>
      </button>
    </div>
  </div>
</div>