config/routes.rb
Rails.application.routes.draw do
  get "user_mfa_sessions/new"
  get "user_mfa_sessions/create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "posts#index"
  # root "posts#index"

  resources :users, only: %i[new create destroy] do
    member do
      get :activate
    end
  end
  resources :beatboxers
  resources :posts do
    get :bookmarks, on: :collection
    resource :bookmarks, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resource :profile, only: %i[show edit update]

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_reloading_data

  def create
    save_comment = @post.comments.build(comment_params)

    if save_comment.save
      flash.now[:notice] = "コメントの投稿に成功しました！"
      render "posts/show", status: :created
    else
      flash.now[:alert] = "コメントの投稿に失敗しました！"
      render "posts/show", status: :unprocessable_entity
    end
  end

  def destroy
    comment_destroy = Comment.find(params[:id])

    if comment_destroy.destroy
      flash.now[:notice] = "コメントの削除に成功しました！"
      render "posts/show", status: :created
    else
      flash.now[:alert] = "コメントの削除に失敗しました！"
      render "posts/show", status: :bad_request
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id, post_id: params[:post_id])
  end

  def set_reloading_data
    @post = Post.find(params[:post_id])
    @comment = Comment.new()
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    @bookmarked_post = current_user.bookmark_posts.pluck(:id)
    gon.render_url = "/posts/#{params[:post_id]}"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>
    <div class="card w-full md:w-[490px] shadow-sm mb-2">
        <div class="card-body flex flex-row items-start gap-4">
            <div class="mr-1">
                <%= image_tag comment.user.avatar_url, class: "skeleton h-16 w-16 shrink-0 rounded-full" %>
            </div>
            <div class="flex flex-col gap-1 w-4/6">
                <div class="flex flex-row items-start">
                    <h2 class="text-lg font-semibold line-clamp-2" style="overflow-wrap: break-word;">
                        <%= comment.user.name %>
                    </h2>
                </div>
                <p class="text-sm text-gray-600" style="overflow-wrap: break-word;">
                    <%= comment.body %>
                </p>
                <% if current_user.id == comment.user.id %>
                    <%= link_to image_tag("trash_can_icon.svg", class: "mt-2 ml-2 w-auto h-5 absolute top-7 right-5"), post_comment_path(@post, comment), method: :delete, data: { turbo_method: :delete } %>
                <% end %>
            </div>
        </div>
    </div>
<% end %>

app/views/comments/_comments.html.erb
<% @comments.each do |comment| %>
    <div class="card w-1/3 shadow-sm mb-2">
        <div class="card-body flex flex-row items-start gap-4">
            <div class="mr-1">
                <%= image_tag comment.user.avatar_url, class: "skeleton h-16 w-16 shrink-0 rounded-full" %>
            </div>
            <div class="flex flex-col gap-1 w-5/6">
                <div class="flex flex-row items-start">
                    <h2 class="text-lg font-semibold line-clamp-2" style="overflow-wrap: break-word;">
                        <%= comment.user.name %>
                    </h2>
                    <%= link_to image_tag("trash_can_icon.svg", class: "mt-2 ml-2 w-5 h-auto"), post_comment_path(@post, comment), method: :delete, data: { turbo_method: :delete } %>
                </div>
                <p class="text-sm text-gray-600" style="overflow-wrap: break-word;">
                    <%= comment.body %>
                </p>
            </div>
        </div>
    </div>
<% end %>

app/views/comments/_form.html.erb
<fieldset class="fieldset">
  <%= form_with model:[@post,@comment], html: { class: "flex gap-6 items-end" } do |f| %>
    <%= f.text_field :body, class: "textarea text-base dark:text-white h-20 md:h-30 w-8/10 md:w-[500px] textarea-primary", :placeholder => "入力してください" %>
    <%= f.submit "投稿", class: "btn btn-base md:btn-lg btn-primary self-end" %>
  <% end %>
</fieldset>