config/routes.rb
Rails.application.routes.draw do
  get "user_mfa_sessions/new"
  get "user_mfa_sessions/create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "posts#index"
  # root "posts#index"

  resources :users, only: %i[new create destroy] do
    member do
      get :activate
    end
  end
  resources :beatboxers
  resources :posts do
    get :bookmarks, on: :collection
    resource :bookmarks, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resource :profile, only: %i[show edit update]

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :user_id, uniqueness: { scope: :post_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :bookmarks, dependent: :destroy

    validates :youtube_video, presence: true
    validates :title, presence: true, length: { maximum: 255 }
    validates :body, presence: true, length: { maximum: 65535 }

    def bookmark_by?(user)
        bookmarks.where(user_id: user).exists?
    end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  acts_as_google_authenticated drift: 20, lookup_token: :mfa_session_token, issuer: "beatboxer-collection.onrender.com"
  after_create do |created_record|
    created_record.set_google_secret
  end

  has_many :beatboxers
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post

  mount_uploader :avatar, AvatarUploader

  with_options presence: true do
    validates :name
    validates :email
  end

  with_options if: -> { new_record? || changes[:crypted_password] } do
    validates :password, length: { minimum: 8 }
    validates :password, confirmation: true
    validates :password_confirmation, presence: true
  end

  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def own?(object)
    id = object.user_id
  end

  def bookmark(post)
    bookmark_posts << post
  end

  def unbookmark(post)
    bookmark_posts.delete(post)
  end

  def bookmark?(post)
    bookmark_posts.exists?(post.id)
  end
end

app/models/user_mfa_session.rb
class UserMfaSession < GoogleAuthenticatorRails::Session::Base
  # 一旦、親クラスのメソッド継承のみが目的なので記載なし
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_reloading_data

  def create
    save_comment = @post.comments.build(comment_params)

    if save_comment.save
      flash.now[:notice] = "コメントの投稿に成功しました！"
      render "posts/show", status: :created
    else
      flash.now[:alert] = "コメントの投稿に失敗しました！"
      render "posts/show", status: :unprocessable_entity
    end
  end

  def destroy
    comment_destroy = Comment.find(params[:id])

    if comment_destroy.destroy
      flash.now[:notice] = "コメントの削除に成功しました！"
      render "posts/show", status: :created
    else
      flash.now[:alert] = "コメントの削除に失敗しました！"
      render "posts/show", status: :bad_request
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id, post_id: params[:post_id])
  end

  def set_reloading_data
    @post = Post.find(params[:post_id])
    @comment = Comment.new()
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    @bookmarked_post = current_user.bookmark_posts.pluck(:id)
    gon.render_url = "/posts/#{params[:post_id]}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    skip_before_action :require_login, only: [ :index ]
    skip_before_action :check_mfa, only: [ :index ]
    before_action :set_bookmarks_data, only: [ :bookmarks, :index, :show ]

    def bookmarks
        if @bookmarked_post.blank?
            flash[:alert] = "ブックマークが登録されていません！"
            redirect_to root_path
            return
        end

        @bookmark_list = Post.where(id: current_user.bookmarks.pluck(:post_id)).page(params[:page]).per(12)
    end

    def index
        @posts = Post.order(id: :desc).page(params[:page]).per(12)
    end

    def show
        @post = Post.find(params[:id])
        @comment = Comment.new
        @comments = @post.comments.includes(:user).order(created_at: :desc)
    end

    def new
        @post = Post.new
    end

    def create
        post = Post.new(post_params)
        if post.save
            flash[:notice] = "投稿しました！"
            redirect_to root_path
        else
            flash.now[:alert] = "投稿できませんでした！"
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private

    def post_params
      params.require(:post).permit(:title, :youtube_video, :body).merge(user_id: current_user.id)
    end

    def set_bookmarks_data
        if current_user
            @bookmarked_post = current_user.bookmark_posts.pluck(:id)
        end
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash.now[:notice] = "ユーザーを更新しました！"
      render :edit, status: :created
    else
      flash.now[:alert] = "ユーザーを更新できませんでした！"
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login
  skip_before_action :check_mfa

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    user.avatar = File.open(Rails.root.join("app/assets/images/default_profile_image.png"))

    if user.save
      flash[:notice] = "仮登録を完了しました。メールアドレスをご確認ください！"
      redirect_to root_path
    else
      flash.now[:alert] = "仮登録に失敗しました！"
      render :new, status: :unprocessable_entity
    end
  end

  def activate
    if (user = User.load_from_activation_token(params[:id]))
      user.update(activation_state: "active")
      flash[:notice] = "ユーザー登録が完了しました！"
      redirect_to login_path
    else
      flash.now[:alert] = "ユーザー登録に失敗しました！"
      not_authenticated
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beatboxers_helper.rb
module BeatboxersHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def find_youtube_url(youtube_video)
      if youtube_video.include?("https://youtu.be/")
        youtube_video.gsub("https://youtu.be/", "")
        # "https://youtu.be/WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
      else youtube_video.include?("https://www.youtube.com/watch?v=")
        youtube_video.gsub("https://www.youtube.com/watch?v=", "")
        # "https://www.youtube.com/watch?v=WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
      end
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/youtube_videos_helper.rb
module YoutubeVideosHelper
end

app/views/shared/_footer.html.erb
<footer class="footer sm:footer-horizontal bg-neutral text-neutral-content items-center p-4 mt-auto">
  <aside class="grid-flow-col items-center">
    <%= image_tag "logo.png", class: "h-30 w-auto"%>
    <p>Copyright © 2025 BBX Hub - All right reserved</p>
  </aside>
  <nav class="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
    <%= link_to "プライバシーポリシー", "" %>
    <%= link_to "利用規約", "" %>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header>
    <div class="navbar bg-neutral text-primary-content" style="height: 140px;">
        <!--ヘッダー左サイドのブロック-->
        <div class="navbar-start">
            <div class="dropdown">
                <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-24 w-24" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /> </svg>
                </div>
                <ul
                    tabindex="0"
                    class="menu menu-sm dropdown-content bg-white rounded-box z-1 mt-3 w-52 p-2 secondary text-black">
                    <li><%= link_to "プロフィール", profile_path %></li>
                    <li><%= link_to "ブックマーク", bookmarks_posts_path %></li>
                    <% if current_user %>
                        <li><%= link_to "新規投稿", new_post_path %></li>
                        <li><%= link_to "ログアウト", logout_path, method: :delete, data: { turbo_method: :delete } %></li>
                    <% else %>
                        <li><%= link_to "ユーザー登録", new_user_path %></li>
                        <li><%= link_to "ログイン", login_path %></li>
                    <% end %>
                </ul>
            </div>
        </div>

        <!--ヘッダーのセンターのブロック-->
        <div class="navbar-center">
                <%= link_to root_path do %>
                    <%= image_tag 'tittle.png', class: "w-75 h-auto md:w-90" %>
                <% end %>
        </div>

        <!--ヘッダーの右サイドのブロック-->
        <div class="navbar-end">
            <div class="hidden md:block">
                <% if current_user %>
                    <%= link_to "新規投稿", new_post_path, class: "btn btn-secondary btn-lg", style: "margin-right: 10px;"%>
                    <%= link_to "ログアウト", logout_path, data: { turbo_method: :delete }, class: "btn btn-secondary btn-lg" %>
                <% else %>
                    <%= link_to "ユーザー登録", new_user_path, class: "btn btn-secondary btn-lg", style: "margin-right: 10px;"%>
                    <%= link_to "ログイン", login_path, class: "btn btn-secondary btn-lg"%>
                <% end %>
            </div>
        </div>
    </div>
</header>